spring:
#  config:
#    import: file:/home/samit/workspace/homelab/config/application.yml
#    additional-location: ""
#    location: ""
  application:
    name: spring-cloud-gateway
  webflux:
    problemdetails:
      enabled: true
#  cloud:
#    gateway:
#      routes:
#        - id: "nginx"
#          uri: http://localhost
#          predicates:
#            - Path=/nginx
#          filters:
#            - SetPath=/
#
#        - id: "todo-web"
#          uri: http://localhost:8080
#          predicates:
#            - Path=/todo
#          filters:
#            - SetPath=/
#
#        - id: "todo"
#          uri: http://localhost:8080
#          predicates:
#            - Path=/todo/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
server:
  port: 9000

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: gateway